version: '3.8'

services:
  db:
    image: postgres:15.4
    container_name: postgres-db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mess_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mess_postgres_data:
