version: '3.8'

services:
  db:
    image: postgres:15.4
    container_name: db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mess_postgres_data:/var/lib/postgresql/data
    networks:
      - movies-network
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    networks:
      - movies-network
    ports:
      - "6379:6379"

  mess_service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mess_service
    depends_on:
      - db
      - redis
    env_file: .env
    networks:
      - movies-network
    ports:
      - "8080:8080"

  tests:
      build: ./tests/functional
      container_name: tests
      networks:
        - movies-network
      environment:
        - PYTHONUNBUFFERED=1
      depends_on:
        - mess_service
      env_file: .env

networks:
  movies-network:
    driver: bridge

volumes:
  mess_postgres_data:
